apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: test
spec:
  meshConfig:
    enableTracing: true
    accessLogFile: /dev/stdout
    accessLogEncoding: 'JSON'
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    accessLogFormat: |
          {
            "start_time": "%START_TIME%",
            "method": "%REQ(:METHOD)%",
            "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
            "protocol": "%PROTOCOL%",
            "response_code": "%RESPONSE_CODE%",
            "response_flags": "%RESPONSE_FLAGS%",
            "response_code_details": "%RESPONSE_CODE_DETAILS%",
            "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",
            "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
            "bytes_received": "%BYTES_RECEIVED%",
            "bytes_sent": "%BYTES_SENT%",
            "duration": "%DURATION%",
            "upstream_service_time": "%REQ(x-envoy-upstream-service-time)%",
            "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
            "user_agent": "%REQ(USER-AGENT)%",
            "request_id": "%REQ(X-REQUEST-ID)%",
            "authority": "%REQ(:AUTHORITY)%",
            "upstream_host": "%UPSTREAM_HOST%",
            "upstream_cluster": "%UPSTREAM_CLUSTER%",
            "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
            "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
            "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
            "requested_server_name": "%REQUESTED_SERVER_NAME%",
            "route_name": "%ROUTE_NAME%",
            "x-b3-traceid": "%REQ(x-b3-traceid)%",
            "x-b3-spanid": "%REQ(x-b3-spanid)%"
          }
  components:
    cni:
      enabled: false
    pilot:
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.topologySpreadConstraints
            value:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app: istiod
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app: istiod
          - path: spec.template.spec.terminationGracePeriodSeconds
            value: 10

        hpaSpec:
          maxReplicas: 5
          minReplicas: 3

  values:
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
