apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: default
spec:
  ports:
  - name: http
    port: 9086
    protocol: TCP
    targetPort: 9086
  selector:
    application: admin-api
  topologyKeys:
    - 'kubernetes.io/hostname'
    - 'topology.kubernetes.io/zone'
    - 'topology.kubernetes.io/region'
    - '*'
